import {device,capacity,switchCodes,Editor,parse,validate,get,key,count,limit,code,codes,pasteEntries,tsv,MAX_BYTES} from './model.mjs';
import {languages,translate} from './i18n.mjs';
const $=id=>document.getElementById(id);let language='en';try{language=localStorage.getItem('namesLanguage')||'en';}catch{}
if(!languages[language])language='en';
let editor=null,list=1,preset=1,modeView=false,query='',invalid=new Set(),revision=0,saved=-1,downloaded=-1,saveTimer,saveChain=Promise.resolve(),draft=null,pasting=null,focusGroup=0;
let draftDevice='quadCortexMini';
const currentCode=p=>code(p,editor?.archive);
const t=k=>translate(k,language);
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
function error(key){$('error').textContent=key&&t(key)===key?t('invalidFile'):t(key);$('error').hidden=!key;}
function guardView(){if(invalid.size){error('invalidDraft');return false;}return true;}
function listLabel(id){return id===0?'Factory Presets':id===1?'My Presets':`${t('setlist')} ${id-1}`;}
function address(f){return f.kind==='mode'?['PRESET','SCENE','STOMP'][f.index]:`${listLabel(f.setlist)}${f.preset?` / ${currentCode(f.preset)}`:''}${f.index!=null?` / ${switchCodes(editor?.archive)[f.index]} / ${t(f.kind)}`:''}`;}
function localize(){document.documentElement.lang=language;$('language').value=language;$('language').ariaLabel=t('language');document.querySelectorAll('[data-t]').forEach(n=>n.textContent=t(n.dataset.t));$('search').placeholder=t('search');document.title=`${t('title')} · Cortex Remote`;if(editor)render();}
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('cortexRemoteNames',1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function storage(action,value,target=draftDevice){const d=await db();return new Promise((resolve,reject)=>{const tr=d.transaction('drafts',action==='read'?'readonly':'readwrite'),s=tr.objectStore('drafts');let r=action==='read'?s.get(target==='quadCortexMini'?'current':target):action==='delete'?s.delete(target==='quadCortexMini'?'current':target):s.put(value,target==='quadCortexMini'?'current':target);let result;r.onsuccess=()=>result=r.result;tr.oncomplete=()=>{d.close();resolve(result);};tr.onerror=()=>{d.close();reject(tr.error);};tr.onabort=()=>{d.close();reject(tr.error);};});}
function status(k){$('saveStatus').textContent=t(k);}
function controls(){if(!editor)return;$('download').disabled=invalid.size>0;$('undo').disabled=!editor.undoStack.length;$('redo').disabled=!editor.redoStack.length;$('editCount').textContent=`${editor.archive.webNameEdits.changes.length} ${t('edits')}`;}
function changed(){revision++;error('');controls();status('saving');clearTimeout(saveTimer);const r=revision,document=structuredClone(editor.archive),target=device(editor.archive);saveTimer=setTimeout(()=>{saveChain=saveChain.catch(()=>{}).then(()=>storage('write',document,target)).then(()=>{if(target===draftDevice){draft=document;$('resume').hidden=false;}if(r===revision){saved=r;status('saved');}}).catch(()=>status('storageError'));},400);}
function fieldInput(field,selected=false){const owner=editor;const value=get(editor.archive.names,field)??'',input=el('input');input.value=value;input.autocomplete='off';input.spellcheck=false;input.dataset.field=key(field);input.ariaLabel=address(field);input.title=`${address(field)} · ${count(value)} / ${limit(field)}${count(value)>limit(field)?` · ${t('legacy')}`:''}`;if(selected)input.classList.add('selected');let group;
 input.addEventListener('focus',()=>{if(owner!==editor)return;group=++focusGroup;if(field.kind==='preset'&&!invalid.size){preset=field.preset;document.querySelectorAll('#presetTable input.selected').forEach(x=>x.classList.remove('selected'));input.classList.add('selected');renderDetails();}});
 const update=()=>{if(owner!==editor)return;if(input.isComposing)return;try{editor.apply([{field,value:input.value}],group);invalid.delete(key(field));input.setAttribute('aria-invalid','false');input.title=`${address(field)} · ${count(input.value)} / ${limit(field)}`;changed();}catch(e){invalid.add(key(field));input.setAttribute('aria-invalid','true');error(e.message);controls();}};
 input.addEventListener('input',e=>{if(!e.isComposing)update();});input.addEventListener('compositionend',update);
 input.addEventListener('blur',()=>{if(owner!==editor)return;if(!invalid.has(key(field)))input.value=get(editor.archive.names,field)??'';});
 input.addEventListener('paste',e=>{if(owner!==editor)return;const text=e.clipboardData.getData('text/plain');if(!/[\t\r\n]/.test(text))return;e.preventDefault();if(query){error('filteredPaste');return;}if(!guardView())return;try{pasting={rows:tsv(text),field};$('clearBlanks').checked=false;previewPaste();$('pasteDialog').showModal();}catch(err){error(err.message);}});
 return input;
}
function render(){
 $('workspace').hidden=false;$('setlists').replaceChildren();for(let id=0;id<13;id++){const b=el('button',listLabel(id),!modeView&&id===list?'active':'');b.dataset.setlist=id;b.title=editor.archive.names.setlists?.[id]?.name??listLabel(id);b.onclick=()=>{if(!guardView())return;list=id;modeView=false;render();};$('setlists').append(b);}
 $('modes').classList.toggle('active',modeView);$('tableTitle').replaceChildren();$('presetTable').replaceChildren();
 const a=editor.archive;$('activeDevice').textContent=device(a)==='quadCortex'?'Quad Cortex':'Quad Cortex mini';$('summary').textContent=`${a.favorites.addresses.length} ${t('favorites')} · ${a.feedback.mappings.length} ${t('mappings')} · ${a.layout.order.length-a.layout.hidden.length} ${t('panels')}`;
 if(modeView){$('tableTitle').append(el('h2',t('modes')));for(let index=0;index<3;index++){const row=el('div',null,'mode-row');row.append(el('label',['PRESET','SCENE','STOMP'][index]),fieldInput({kind:'mode',index}));$('presetTable').append(row);}$('detailPane').hidden=true;}
 else{$('detailPane').hidden=false;$('tableTitle').append(el('h2',`${listLabel(list)} · ${t('presets')}`));const lab=el('label',t('setlistName'));lab.append(fieldInput({kind:'setlist',setlist:list}));$('tableTitle').append(lab);
 const table=el('table'),head=el('thead'),hr=el('tr');for(const name of [t('slot'),...[...'ABCDEFGH'].slice(0,capacity(a))])hr.append(el('th',name));head.append(hr);table.append(head);const body=el('tbody');let rows=0;
 for(let slot=1;slot<=256/capacity(a);slot++){const addresses=Array.from({length:capacity(a)},(_,i)=>(slot-1)*capacity(a)+i+1);if(query&&!addresses.some(p=>`${currentCode(p)} ${get(a.names,{kind:'preset',setlist:list,preset:p})??''}`.toLocaleLowerCase(language).includes(query.toLocaleLowerCase(language))))continue;
 const tr=el('tr');tr.append(el('th',String(slot)));for(const p of addresses){const td=el('td');td.append(fieldInput({kind:'preset',setlist:list,preset:p},p===preset));tr.append(td);}body.append(tr);rows++;}table.append(body);$('presetTable').append(rows?table:el('p',t('noResults'),'mode-row'));renderDetails();}
 controls();
}
function renderDetails(){const pane=$('detailPane');pane.replaceChildren(el('p',currentCode(preset),'code'),el('h2',t('details')),el('p',get(editor.archive.names,{kind:'preset',setlist:list,preset})??t('preset')));const table=el('table'),head=el('tr');for(const s of ['',t('scene'),t('stomp')])head.append(el('th',s));const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');for(let index=0;index<8;index++){const row=el('tr');row.append(el('th',switchCodes(editor?.archive)[index]));for(const kind of ['scene','stomp']){const td=el('td');td.append(fieldInput({kind,setlist:list,preset,index}));row.append(td);}body.append(row);}table.append(body);pane.append(table,el('p',t('pasteHint')));}
function previewPaste(){try{const entries=pasteEntries(pasting.rows,pasting.field,$('clearBlanks').checked,editor.archive);pasting.entries=entries;$('pastePreview').replaceChildren(...entries.map(e=>el('div',`${address(e.field)} → ${e.value||t('remove')}`)));$('pasteError').textContent='';$('applyPaste').disabled=false;}catch(e){pasting.entries=null;$('pastePreview').replaceChildren();$('pasteError').textContent=t(e.message);$('applyPaste').disabled=true;}}
function start(a,blank=false){editor=new Editor(a,blank);draftDevice=device(a);$('device').value=draftDevice;invalid.clear();list=1;preset=1;modeView=false;query='';$('search').value='';revision++;saved=-1;downloaded=-1;render();changed();}
function replaceAllowed(){return !editor||confirm(t('replace'));}
$('open').onclick=()=>{if(replaceAllowed()){$('file').value='';$('file').click();}};
$('file').onchange=async()=>{try{const file=$('file').files[0];if(!file)return;if(file.size>MAX_BYTES)throw new Error('tooLarge');start(parse(await file.text()));}catch(e){error(e.message);}};
$('blank').onclick=async()=>{if(!replaceAllowed())return;try{const r=await fetch(draftDevice==='quadCortex'?'blank-qc.json':'blank.json');if(!r.ok)throw new Error('invalidFile');start(validate(await r.json()),true);}catch(e){error(e.message);}};
$('device').onchange=async()=>{if(editor&&!replaceAllowed()){$('device').value=draftDevice;return;}clearTimeout(saveTimer);await saveChain;if(editor){try{await storage('write',structuredClone(editor.archive),device(editor.archive));}catch{status('storageError');return;}}editor=null;invalid.clear();$('workspace').hidden=true;$('download').disabled=true;draftDevice=$('device').value;draft=null;$('resume').hidden=true;try{const value=await storage('read');if(value){draft=validate(value);$('resume').hidden=false;}}catch{status('storageError');}};
$('resume').onclick=()=>{if(!draft||!replaceAllowed())return;try{start(validate(draft));}catch(e){error(e.message);}};
$('download').onclick=()=>{if(!guardView())return;try{const blob=new Blob([editor.download()],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=`CortexRemote-Names-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);downloaded=revision;}catch(e){error(e.message);}};
$('undo').onclick=()=>{invalid.clear();editor.undo();render();changed();};$('redo').onclick=()=>{invalid.clear();editor.redo();render();changed();};
$('search').oninput=()=>{if(!guardView())return;query=$('search').value;render();};$('modes').onclick=()=>{if(guardView()){modeView=true;render();}};
$('language').onchange=()=>{if(!guardView()){$('language').value=language;return;}language=$('language').value;try{localStorage.setItem('namesLanguage',language);}catch{}localize();};
$('clearBlanks').onchange=previewPaste;$('cancelPaste').onclick=()=>$('pasteDialog').close();$('applyPaste').onclick=()=>{try{if(pasting.entries){editor.apply(pasting.entries);render();changed();$('pasteDialog').close();}}catch(e){$('pasteError').textContent=t(e.message);}};
$('clearDraft').onclick=async()=>{if(!confirm(t('clearConfirm')))return;clearTimeout(saveTimer);try{await saveChain;await storage('delete');saved=-1;draft=null;$('resume').hidden=true;status('cleared');}catch{status('storageError');}};
window.addEventListener('beforeunload',e=>{if(editor&&(invalid.size||revision>saved&&revision>downloaded)){e.preventDefault();e.returnValue='';}});
localize();
if(typeof Intl.Segmenter!=='function'){error('browser');for(const id of ['blank','open','resume'])$(id).disabled=true;}
else storage('read').then(value=>{if(value){draft=validate(value);$('resume').hidden=false;}}).catch(()=>status('storageError'));
