const rows = {
 title:['Names Editor','이름 편집기','名前エディター','Namenseditor'], subtitle:['Your sounds. Clearly named.','사운드에 알아보기 쉬운 이름을.','サウンドに、わかりやすい名前を。','Deine Sounds. Klar benannt.'],
 intro:['Edit on your computer, then bring your names to Cortex Remote. Files stay in this browser.','컴퓨터에서 이름을 편집하고 Cortex Remote로 가져오세요. 파일은 이 브라우저에만 저장됩니다.','パソコンで名前を編集して、Cortex Remoteに読み込めます。ファイルはこのブラウザ内に保存されます。','Bearbeite Namen am Computer und importiere sie in Cortex Remote. Dateien bleiben in diesem Browser.'],
 open:['Open app backup','앱 백업 열기','アプリのバックアップを開く','App-Backup öffnen'],blank:['Start blank','빈 구성으로 시작','空の構成で開始','Leer beginnen'],resume:['Resume local draft','저장된 초안 이어서 편집','ローカル下書きを再開','Lokalen Entwurf fortsetzen'],clearDraft:['Clear local draft','로컬 초안 삭제','ローカル下書きを削除','Lokalen Entwurf löschen'],
 download:['Download JSON','JSON 다운로드','JSONをダウンロード','JSON herunterladen'],undo:['Undo','실행 취소','元に戻す','Rückgängig'],redo:['Redo','다시 실행','やり直す','Wiederholen'],
 setlists:['Setlists','세트리스트','セットリスト','Setlists'],setlist:['Setlist','세트리스트','セットリスト','Setlist'],setlistName:['Setlist name','세트리스트 이름','セットリスト名','Setlist-Name'],modes:['Mode names','모드 이름','モード名','Modusnamen'],
 presets:['Preset names','프리셋 이름','プリセット名','Preset-Namen'],slot:['Slot','슬롯','スロット','Platz'],preset:['Preset','프리셋','プリセット','Preset'],scene:['Scene name','씬 이름','シーン名','Szenenname'],stomp:['Stomp name','스톰프 이름','Stomp名','Stomp-Name'],details:['Scene & Stomp names','씬 및 스톰프 이름','シーンとStompの名前','Szenen- und Stomp-Namen'],
 search:['Search code or name','코드 또는 이름 검색','コードまたは名前で検索','Code oder Name suchen'],noResults:['No matching presets','일치하는 프리셋 없음','一致するプリセットはありません','Keine passenden Presets'],
 help:['How it works','사용 방법','使い方','So funktioniert’s'],steps:['1. Export configuration from the app, or start blank. 2. Edit names; paste tables from a spreadsheet. 3. Download JSON and transfer it to your iPad using Files or iCloud Drive. 4. Import in Settings and choose Apply edited names only.','1. 앱에서 구성을 내보내거나 빈 구성으로 시작하세요. 2. 이름을 편집하고 스프레드시트 표를 붙여넣으세요. 3. JSON을 다운로드한 후 파일 앱이나 iCloud Drive로 iPad에 전송하세요. 4. 설정에서 가져온 후 편집한 이름만 적용을 선택하세요.','1. アプリから構成を書き出すか、空の構成で開始します。2. 名前を編集し、表計算ソフトから貼り付けます。3. JSONをダウンロードし、ファイルまたはiCloud DriveでiPadに転送します。4. 設定で読み込み、編集した名前のみを適用します。','1. Konfiguration aus der App exportieren oder leer beginnen. 2. Namen bearbeiten und Tabellen einfügen. 3. JSON herunterladen und über Dateien oder iCloud Drive auf das iPad übertragen. 4. In den Einstellungen importieren und nur bearbeitete Namen anwenden.'],
 compatibility:['Selective name import requires the updated app. Older app versions restore the entire configuration. These labels do not rename presets on your mini.','이름만 가져오려면 업데이트된 앱이 필요합니다. 이전 버전은 전체 구성을 복원합니다. 이 이름은 mini의 프리셋 이름을 변경하지 않습니다.','名前のみの読み込みには更新版アプリが必要です。旧バージョンでは構成全体が復元されます。mini本体のプリセット名は変更されません。','Der selektive Import benötigt die aktualisierte App. Ältere Versionen stellen die gesamte Konfiguration wieder her. Die Namen auf deinem mini werden nicht geändert.'],
 private:['Local editing · No upload · No account','로컬 편집 · 업로드 없음 · 계정 불필요','ローカル編集 · アップロードなし · アカウント不要','Lokal bearbeiten · Kein Upload · Kein Konto'],
 saved:['Saved in this browser','이 브라우저에 저장됨','このブラウザに保存済み','In diesem Browser gespeichert'],saving:['Saving locally…','로컬에 저장 중…','ローカルに保存中…','Wird lokal gespeichert…'],storageError:['Local saving is unavailable. Download JSON to keep your work.','로컬 저장을 사용할 수 없습니다. 작업을 보관하려면 JSON을 다운로드하세요.','ローカル保存を利用できません。JSONをダウンロードして作業を保存してください。','Lokales Speichern ist nicht verfügbar. Lade JSON herunter, um deine Arbeit zu sichern.'],
 cleared:['Local draft cleared. Download to keep current work.','로컬 초안을 삭제했습니다. 현재 작업을 보관하려면 다운로드하세요.','ローカル下書きを削除しました。現在の作業を残すにはダウンロードしてください。','Lokaler Entwurf gelöscht. Lade die aktuelle Arbeit herunter, um sie zu behalten.'],
 edits:['edited names','개 이름 편집됨','件の編集','bearbeitete Namen'],summary:['Other settings — preserved, read-only','기타 설정 — 유지됨, 읽기 전용','その他の設定 — 保持・読み取り専用','Weitere Einstellungen — unverändert, schreibgeschützt'],
 favorites:['Favorites','즐겨찾기','お気に入り','Favoriten'],mappings:['MIDI mappings','MIDI 매핑','MIDI-Zuordnungen','MIDI-Zuordnungen'],panels:['visible panels','개 표시 패널','表示パネル','sichtbare Panels'],
 pasteTitle:['Review spreadsheet paste','스프레드시트 붙여넣기 검토','表の貼り付けを確認','Tabelleneinfügung prüfen'],pasteHint:['Paste a rectangle of names into the focused cell. Blank cells are ignored unless selected below.','선택한 셀에 이름 표를 붙여넣으세요. 아래 옵션을 선택하지 않으면 빈 셀은 무시됩니다.','選択したセルに名前の表を貼り付けます。下の設定を選ばない限り空欄は無視されます。','Füge einen rechteckigen Namensbereich ab der ausgewählten Zelle ein. Leere Zellen werden standardmäßig ignoriert.'],
 clearBlanks:['Clear names for blank cells','빈 셀에 해당하는 이름 지우기','空欄の名前を消去','Namen für leere Zellen löschen'],apply:['Apply paste','붙여넣기 적용','貼り付けを適用','Einfügen anwenden'],cancel:['Cancel','취소','キャンセル','Abbrechen'],remove:['Clear name','이름 지우기','名前を消去','Name löschen'],
 replace:['Replace current work? Download first if you want to keep it.','현재 작업을 바꿀까요? 보관하려면 먼저 다운로드하세요.','現在の作業を置き換えますか？残すには先にダウンロードしてください。','Aktuelle Arbeit ersetzen? Lade sie vorher herunter, wenn du sie behalten möchtest.'],
 clearConfirm:['Delete the saved draft from this browser?','이 브라우저에 저장된 초안을 삭제할까요?','このブラウザの保存済み下書きを削除しますか？','Gespeicherten Entwurf aus diesem Browser löschen?'],
 invalidFile:['Invalid or inconsistent configuration. Nothing was replaced.','유효하지 않거나 일관되지 않은 구성입니다. 변경된 내용은 없습니다.','構成が無効か矛盾しています。何も置き換えていません。','Ungültige oder widersprüchliche Konfiguration. Nichts wurde ersetzt.'],
 oldVersion:['Open this backup in the current app and export it again. The editor requires backup version 3.','현재 앱에서 이 백업을 가져온 후 다시 내보내세요. 편집기는 백업 버전 3이 필요합니다.','現在のアプリで読み込み、再度書き出してください。エディターにはバックアップバージョン3が必要です。','Öffne dieses Backup in der aktuellen App und exportiere es erneut. Der Editor benötigt Backup-Version 3.'],
 tooLarge:['The maximum file size is 8 MiB.','최대 파일 크기는 8 MiB입니다.','ファイルの上限は8 MiBです。','Die maximale Dateigröße beträgt 8 MiB.'],tooLong:['Name is too long. Shorten it before continuing.','이름이 너무 깁니다. 계속하려면 줄여주세요.','名前が長すぎます。短くしてください。','Name zu lang. Bitte kürzen.'],
 invalidPaste:['Paste a rectangular table of names without column headers.','열 제목 없이 직사각형 이름 표를 붙여넣으세요.','列見出しを除いた長方形の名前の表を貼り付けてください。','Füge eine rechteckige Namenstabelle ohne Spaltenüberschriften ein.'],pasteBounds:['The pasted table exceeds the available rows or columns.','붙여넣은 표가 사용 가능한 행 또는 열을 초과합니다.','貼り付け範囲が行または列を超えています。','Der eingefügte Bereich überschreitet die verfügbaren Zeilen oder Spalten.'],filteredPaste:['Clear the search before pasting a table.','표를 붙여넣기 전에 검색을 지우세요.','表を貼り付ける前に検索を解除してください。','Leere die Suche, bevor du eine Tabelle einfügst.'],
 browser:['This browser needs Intl.Segmenter support. Update your browser to edit names safely.','안전한 이름 편집을 위해 Intl.Segmenter를 지원하는 최신 브라우저로 업데이트하세요.','安全に編集するにはIntl.Segmenter対応のブラウザに更新してください。','Aktualisiere deinen Browser auf eine Version mit Intl.Segmenter-Unterstützung.'],
 invalidDraft:['Fix highlighted names before downloading or changing views.','다운로드하거나 화면을 바꾸기 전에 강조된 이름을 수정하세요.','ダウンロードや画面切り替えの前に、強調された名前を修正してください。','Korrigiere markierte Namen vor dem Herunterladen oder Ansichtswechsel.'],
 legacy:['Existing long name preserved until edited','기존의 긴 이름은 편집하기 전까지 유지됩니다','既存の長い名前は編集するまで保持されます','Vorhandener langer Name bleibt bis zur Bearbeitung erhalten'],
 support:['Support','지원','サポート','Support'],privacy:['Privacy','개인정보 보호','プライバシー','Datenschutz'],language:['Language','언어','言語','Sprache']
};
rows.mappings[2]='MIDIマッピング';
export const languages={en:'English',ko:'한국어',ja:'日本語',de:'Deutsch'};
export const translate=(key,lang='en')=>rows[key]?.[['en','ko','ja','de'].indexOf(lang)]??rows[key]?.[0]??key;
export const translationKeys=Object.keys(rows);
